# Disabling the IPv6
 
    - name: Turn off IPv6     
      lineinfile: dest=/etc/sysconfig/network
                  regexp="^NETWORKING_IPV6"
                  line="NETWORKING_IPV6=no"  
                  regexp="^IPV6INIT"
                  line="IPV6INIT=no"
      notify:
      - restart network 
